---
title: "TidyTuesday"
format: html
---

```{r}
tuesdata <- tidytuesdayR::tt_load('2024-06-04')
## OR
tuesdata <- tidytuesdayR::tt_load(2024, week = 23)

cheeses <- tuesdata$cheeses


```

```{r}

library(tidyverse)
library(packcircles)
library(ggiraph)

df_cheese_country_init <- cheeses |> 
  mutate(
    country = str_replace_all(country, regex("\\b[Aa]nd\\b"), ",")
  ) |> 
  separate_longer_delim(country, delim = ",") |> 
  mutate(
    country = str_trim(country) |> str_to_title()
  ) |> 
  drop_na(country)
  
# need an id of some sort to tie in circle circum data  
df_cheese_country <- df_cheese_country_init |> 
  distinct(cheese, country) |> 
  count(country, name = "country_n") |> 
  mutate(id = row_number())

# start on second tier levels
df_cheese_type <- df_cheese_country_init |> 
  separate_longer_delim(type, ",") |> 
  mutate(
    type = str_trim(type) |> str_to_title()
  ) |> 
  drop_na(type) |> 
  count(country, type, name = "type_n") |>
  left_join(df_cheese_country, by = "country")
  



```

```{r}
outer_packing <- circleProgressiveLayout(df_cheese_country$country_n, sizetype = 'area')
country_summary <- bind_cols(df_cheese_country, outer_packing)

circle_data <- circleLayoutVertices(outer_packing, npoints = 50)
```


```{r}
circle_data <- circle_data |>
  left_join(df_cheese_country, by = "id")
```

```{r}
# plot is weird with labels for some reason
# labels are not working well with the small circles, leaving as hover over for now
labels <- circle_data |>
  group_by(id) |>
  slice(1) |> 
  ungroup()


p <- ggplot(circle_data, aes(x, y)) +
  geom_polygon_interactive(
    aes(
      group = id,
      fill = country,
      tooltip = paste0(country, ": ", country_n, " cheeses"),
      data_id = country
    ),
    color = "white",
    alpha = 0.8
  ) +
  #   geom_text_interactive(
  #   data = labels,
  #   aes(x = x, y = y, label = country, tooltip = country, data_id = country),
  #   size = 3,
  #   color = "black"
  # ) +
  coord_equal() +
  theme_void() +
  theme(legend.position = "none")


girafe(ggobj = p)
```

